# 公共配置文件
# @author <a href="https://github.com/lhccong">程序员聪</a>
spring:
  application:
    name: we-go
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 50MB
      max-request-size: 50MB
server:
  address: 0.0.0.0
  port: 8869
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.cong.wego.controller
kimi:
  api:
    url: https://api.moonshot.cn/v1/chat/completions
    token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTc0NzgyNzAyNSwiaWF0IjoxNzQ1MjM1MDI1LCJqdGkiOiJkMDMyb2tjamMzZjYxbHFsMjFjMCIsInR5cCI6ImFjY2VzcyIsImFwcF9pZCI6ImtpbWkiLCJzdWIiOiJjcTNtZDVyM2Flc3Vob2MxdGV2MCIsInNwYWNlX2lkIjoiY3EzbWQ1cjNhZXN1aG9jMXRldGciLCJhYnN0cmFjdF91c2VyX2lkIjoiY3EzbWQ1cjNhZXN1aG9jMXRldDAiLCJyb2xlcyI6WyJ2aWRlb19nZW5fYWNjZXNzIl19.0aKkPq9wRYZS6TNMHFJd_-FsAO-bQImKa_KHAL9piPW9BO4CNfDBYxe4RSiR-1d3tJID8pk_E0MezYReSIQBKw
    model: moonshot-v1-8k  # 添加模型配置
zhipu:
  api:
    url: https://open.bigmodel.cn/api/paas/v4/chat/completions
    api-key: e55686b8c0c9442ea03c8770f663e320.pK41eeI5luPt8DxT
    model: glm-4